### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by jpaechnatz** [guardianproject/securereader#1]
Crashing after defining a passphrase. 
Cm nightly 13

**Comment by GeitHub** [comment]
same here, I think it has to do with it being Android Marshmallow

**Comment by chross** [comment]
Same here as well.  Using cm13 nightly

**Comment by n8fr8** [comment]
Please see the news here:
https://github.com/guardianproject/ChatSecureAndroid/releases/tag/14.3

Our new project "Zom" is the next-gen of ChatSecure Android, and still offers the encryption feature under the "lock" menu option. It works on Android 6+ at least AOSP.

---

Thanks for being a part of the ChatSecure Android community. We are not actively developing this app anymore, but will continue to fix any critical bugs. ChatSecure for iOS and iPhone WILL CONTINUE ACTIVE DEVELOPMENT!

We are excited to share some great active apps that continue our mission of privacy and security...

Zom is built by the ChatSecure team, and makes it quick & easy for users to connect without a phone number, central servers or requiring any personal data. Zom is also available for iPhones and iPads.

Learn more at https://zom.im

Conversations is the best modern open-source, standards-compliant mobile XMPP client. It is lightweight and supports the OMEMO advanced encryption protocol. Great for advanced users.

Learn more at https://conversations.im

**Comment by jpaechnatz** [comment]
Zom source is where? 
And it does not Close this issue...

**Comment by n8fr8** [comment]
I'm sorry, I was confused about which project this is. You are correct it does not close this issue.

**Comment by walrus543** [comment]
Here is a [log](https://osine.cozycloud.cc/public/files/files/cc9029c7ccb261e669cff3e3c709ec7c/attach/logcat_and_device_info.zip) from my Nexus 5 - AOSP 6.0.1 based ROM.
Oops log removed oO Tell me if you need another one.

**Comment by Armadillux** [comment]
Same here: Crashes on entering passphrase. CM13 on OPX:
See logcat output:

```
11-08 23:35:52.699  8937  8937 E AndroidRuntime: FATAL EXCEPTION: main
11-08 23:35:52.699  8937  8937 E AndroidRuntime: Process: info.guardianproject.courier, PID: 8937
11-08 23:35:52.699  8937  8937 E AndroidRuntime: Theme: themes:{org.cyanogenmod.theme.chooser2=overlay:org.cyanogenmod.hexolibre, com.cyanogenmod.trebuchet=overlay:org.cyanogenmod.hexolibre, com.android.settings=overlay:org.cyanogenmod.hexolibre}
11-08 23:35:52.699  8937  8937 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "EVP_CipherFinal" referenced by "/data/app/info.guardianproject.courier-1/lib/arm/libiocipher.so"...
11-08 23:35:52.699  8937  8937 E AndroidRuntime:    at java.lang.Runtime.loadLibrary(Runtime.java:372)
11-08 23:35:52.699  8937  8937 E AndroidRuntime:    at java.lang.System.loadLibrary(System.java:1076)
11-08 23:35:52.699  8937  8937 E AndroidRuntime:    at info.guardianproject.iocipher.VirtualFileSystem.<clinit>(VirtualFileSystem.java:19)
11-08 23:35:52.699  8937  8937 E AndroidRuntime:    at info.guardianproject.cacheword.IOCipherMountHelper.mount(IOCipherMountHelper.java:42)
11-08 23:35:52.699  8937  8937 E AndroidRuntime:    at info.guardianproject.securereader.SocialReader.initializeFileSystemCache(SocialReader.java:1042)
11-08 23:35:52.699  8937  8937 E AndroidRuntime:    at info.guardianproject.securereader.SocialReader.initialize(SocialReader.java:293)
11-08 23:35:52.699  8937  8937 E AndroidRuntime:    at info.guardianproject.securereader.SocialReader.onCacheWordOpened(SocialReader.java:2018)
11-08 23:35:52.699  8937  8937 E AndroidRuntime:    at info.guardianproject.cacheword.CacheWordHandler.checkCacheWordState(CacheWordHandler.java:330)
11-08 23:35:52.699  8937  8937 E AndroidRuntime:    at info.guardianproject.cacheword.CacheWordHandler.access$100(CacheWordHandler.java:24)
11-08 23:35:52.699  8937  8937 E AndroidRuntime:    at info.guardianproject.cacheword.CacheWordHandler$1.onReceive(CacheWordHandler.java:363)
11-08 23:35:52.699  8937  8937 E AndroidRuntime:    at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:297)
11-08 23:35:52.699  8937  8937 E AndroidRuntime:    at android.support.v4.content.LocalBroadcastManager.access$000(LocalBroadcastManager.java:46)
11-08 23:35:52.699  8937  8937 E AndroidRuntime:    at android.support.v4.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:116)
11-08 23:35:52.699  8937  8937 E AndroidRuntime:    at android.os.Handler.dispatchMessage(Handler.java:102)
11-08 23:35:52.699  8937  8937 E AndroidRuntime:    at android.os.Looper.loop(Looper.java:148)
11-08 23:35:52.699  8937  8937 E AndroidRuntime:    at android.app.ActivityThread.main(ActivityThread.java:5461)
11-08 23:35:52.699  8937  8937 E AndroidRuntime:    at java.lang.reflect.Method.invoke(Native Method)
11-08 23:35:52.699  8937  8937 E AndroidRuntime:    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
11-08 23:35:52.699  8937  8937 E AndroidRuntime:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

```

**Comment by digital-dijjn** [comment]
Same. I put in the passphrase I get a brief glimpse of the initial screen, then it crashes and I am regreeted with the screen asking me to provide my password.

**Comment by digital-dijjn** [comment]
Oh yeah... I'm using copperheados

**Comment by jamestomasino** [comment]
Reporting the same issue. CopperheadOS (N4F26J.2017.01.26.14.27.36) on a Nexus 5X. Courier 0.1.9, installed via F-Droid.

1) I enter the passphrase
2) Phone goes black and vibrates twice
3) App starts and I get a flashing glimpse of the welcome screen
4) Immediately relaunches the window asking for pass phrase

**Comment by ohthreefive** [comment]
identical issue to @jamestomasino ; same hardware, OS and app version too!

**Comment by joeyboon** [comment]
Don't know if it is any help but I have the same problem on my Nexus 5X with copperhead.

**Comment by VonKavalier** [comment]
Same here on OnePlus 3T

**Comment by thiswillbeyourgithub** [comment]
Latest version of FDroid crashed just after entering the passphrase on Lineage OS 14.1 latest nightly. I can't find eveywhere that the project is officially over but I don't find any sign of activity...

PS : As you can see here : https://dev.guardianproject.info/projects/secure-reader
All the developpers and contributers mentionned have not logged on the site for at least a year :(

PS 2 : On FDroid the app has not been updated for 3 years :/
